import { type FormEvent, useState } from 'react'
import { Link, useNavigate } from 'react-router-dom'
import { Header } from '../components/Layout'

export function SignupPage(){const [step,setStep]=useState(1);const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [confirm,setConfirm]=useState('');const [nationality,setNationality]=useState('');const [checked,setChecked]=useState(false);const [errors,setErrors]=useState<string[]>([]);const next=(e:FormEvent)=>{e.preventDefault();const nextErrors=[];if(!email.includes('@'))nextErrors.push('Enter a valid email address');if(password.length<8)nextErrors.push('Min 8 characters, combination of letters, numbers, and symbols');if(password!==confirm)nextErrors.push('Password does not match');if(!nationality)nextErrors.push('Select your nationality');setErrors(nextErrors);if(!nextErrors.length)setStep(2)};return <div className="auth-page"><Header/><main>{step===1?<form className="auth-card" onSubmit={next}><h1>Welcome to Kart</h1><label>E-Mail<div className="email-check"><input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email"/><button type="button" onClick={()=>setChecked(true)}>Check</button></div>{checked&&<small className="safe">Available account</small>}</label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Create a password"/></label><label>Password Confirm<input type="password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Enter password again"/></label><label>Nationality<select value={nationality} onChange={e=>setNationality(e.target.value)}><option value="">Select your nationality</option><option>United States</option><option>Japan</option><option>Singapore</option></select></label>{errors.map(error=><p className="auth-error" key={error}>ⓘ {error}</p>)}<button className="auth-primary">Continue to next step</button><Link to="/login">Log in</Link></form>:<ConsentStep/>}</main></div>}

function ConsentStep(){const [profile,setProfile]=useState('Individual');const [consents,setConsents]=useState([true,false,false]);const navigate=useNavigate();return <section className="auth-card consent-card"><h2>Investor Profile</h2><div className="profile-options"><button className={profile==='Individual'?'active':''} onClick={()=>setProfile('Individual')}><b>Individual</b><span>Standard retail market insight.</span></button><button className={profile==='Institutional'?'active':''} onClick={()=>setProfile('Institutional')}><b>Institutional</b><span>Focus on corporate filings &amp; bulk data.</span></button></div><h2>Required Consents</h2>{['I agree the Terms of Service. (Req.)','I have read and consent to the Privacy Policy. (Req.)','I acknowledge the FSC Information Disclaimer regarding AI-generated insights. (Req.)'].map((label,index)=><label className="consent" key={label}><input type="checkbox" checked={consents[index]} onChange={()=>setConsents(v=>v.map((x,i)=>i===index?!x:x))}/><span>{label}</span></label>)}<button className="auth-primary" disabled={!consents.every(Boolean)} onClick={()=>navigate('/my')}>Create Account ›</button></section>}

export function LoginPage(){const [email,setEmail]=useState('');const [password,setPassword]=useState('');const [error,setError]=useState(false);const navigate=useNavigate();const submit=(e:FormEvent)=>{e.preventDefault();if(email&&password.length>=8)navigate('/my');else setError(true)};return <div className="auth-page"><Header/><main><form className="auth-card login-card" onSubmit={submit}><h1>Welcome Back</h1><label>E-Mail<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="Enter your email"/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Password"/></label>{error&&<p className="auth-error">ⓘ Please check your ID and password again.</p>}<button className="auth-primary">Log in</button><button type="button" className="forgot">Forgot your <u>password?</u></button></form></main></div>}
