import { useState } from 'react'
import { Link } from 'react-router-dom'
import { Header } from '../components/Layout'

const recent=[['News','Semiconductor Exports Surge in April','Negative','High priority','Foreign selling'],['Disclosure','Regulatory Body Probes Short Selling Practices','Earning','High priority','Positive'],['Disclosure','Semiconductor Exports Surge in April','Government','Medium priority','Positive'],['News','Regulatory Body Probes Short Selling Practices','','Medium priority','Listing'],['News','Semiconductor Exports Surge in April','Negative','High priority','Foreign selling']]
const stocks=[['Samsung Electronics','005930 · KOSPI','320,000','-1,003','-1.55%','Near reached'],['SK Hynix','000660 · KOSPI','320,000','-1,003','-1.55%','Near cap'],['NAVER','035420 · KOSPI','320,000','-1,003','-1.55%','Open'],['KT Corporation','030200 · KOSPI','320,000','-1,003','+2.35%','Near cap'],['Samsung SDI','006400 · KOSPI','320,000','-1,003','+3.35%','Open']]

export function MyPage(){const [selected,setSelected]=useState(stocks.map(()=>true));return <div className="my-page"><Header/><main className="page-shell my-shell"><Link className="back-link" to="/">‹&nbsp; Back</Link><section className="profile-row"><img src="/assets/profile.png" alt="Joe Biden"/><div><h1>Joe Biden</h1><div><span>🇺🇸 United States</span><span className="safe">Eligible for 15% treaty rate</span><span>Individual</span></div></div><Link to="/tax">Complete tax filing ›</Link></section><DashboardSection title="Recently viewed" description="News and filings you opened, with their summaries kept for reference."><ActivityList/></DashboardSection><DashboardSection title="My watchlist" description="Add companies with the ♡ button in the search dropdown or on any company page."><div className="watchlist"><header><span>▣ {selected.filter(Boolean).length} selected</span><button onClick={()=>setSelected(stocks.map(()=>false))}>♙</button></header><div className="watch-head"><span>Company</span><span>Price(KRW)</span><span>Change</span><span>%</span><span>Regulatory status</span></div>{stocks.map((stock,index)=><div className="watch-row" key={`${stock[0]}-${index}`}><label><input type="checkbox" checked={selected[index]} onChange={()=>setSelected(v=>v.map((x,i)=>i===index?!x:x))}/><span><b>{stock[0]}</b><small>{stock[1]}</small></span></label><span>{stock[2]}</span><span className="danger-text">{stock[3]}</span><span className={stock[4].startsWith('+')?'safe':'danger'}>{stock[4]}</span><span className={stock[5].startsWith('Near')?'warning-chip':''}>{stock[5]}</span></div>)}<Link to="/stocks/005930">View more watchlist⌄</Link></div></DashboardSection><DashboardSection title="Integrated Intelligence Feed" description="News and filings filtered to your watchlist only."><ActivityList/></DashboardSection></main></div>}

function DashboardSection({title,description,children}:{title:string;description:string;children:React.ReactNode}){return <section className="dashboard-section"><div className="dashboard-title"><div><h2>{title}</h2><p>{description}</p></div><div><button>‹</button><button>›</button></div></div>{children}</section>}
function ActivityList(){return <div className="activity-list">{recent.map((row,index)=><Link to={row[0]==='News'?'/news/fy2025-dividend':'/disclosures/20260814001'} key={index}><div><span>{row[0]}</span><b>{row[1]}</b></div><div>{row.slice(2).filter(Boolean).map((tag,i)=><span className={tag==='Negative'||tag==='High priority'?'priority':tag==='Positive'?'positive':tag==='Medium priority'?'medium':''} key={tag+i}>{tag}</span>)}</div></Link>)}</div>}
